<a href="https://colab.research.google.com/github/sauravgurjar1102-blip/Saurav-Gurjar/blob/main/saurav_sanni.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/adult saurav.csv')
df

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K


In [ ]:
age_array = df["age"].to_numpy()
hours_array = df["hours.per.week"].to_numpy()

print("Age NumPy Array:")
print(age_array[:10])

print("\nHours per Week NumPy Array:")
print(hours_array[:10])

Age NumPy Array:
[90 82 66 54 41 34 38 74 68 41]

Hours per Week NumPy Array:
[40 18 40 40 40 45 40 20 40 60]


In [ ]:
print("First age:", age_array[0])
print("Fifth age:", age_array[4])
print("Last age:", age_array[-1])

First age: 90
Fifth age: 41
Last age: 22


In [ ]:
# Basic Slicing

print("First 10 values of age array:")
print(age_array[:10])

print("\nBasic Slice (index 2 to 6):")
print(age_array[2:7])


First 10 values of age array:
[90 82 66 54 41 34 38 74 68 41]

Basic Slice (index 2 to 6):
[66 54 41 34 38]


In [ ]:
age_array[2:7]

array([66, 54, 41, 34, 38])

In [ ]:
age_25_35 = age_array[(age_array >= 25) & (age_array <= 35)]

print("Ages between 25 and 35:")
print(age_25_35[:20])


Ages between 25 and 35:
[34 32 34 29 33 32 33 32 31 31 26 27 35 35 26 34 25 28 28 33]


In [ ]:
# Basic Slicing vs Advanced (Fancy) Indexing

print("Original Array - First 10 values:")
print(age_array[:10])

# Basic slicing
basic = age_array[0:5]

# Fancy indexing
fancy = age_array[[0, 2, 4]]

print("\nBasic Slicing [0:5]:")
print(basic)

print("\nAdvanced/Fancy Indexing [[0, 2, 4]]:")
print(fancy)


Original Array - First 10 values:
[90 82 66 54 41 34 38 74 68 41]

Basic Slicing [0:5]:
[90 82 66 54 41]

Advanced/Fancy Indexing [[0, 2, 4]]:
[90 66 41]


In [ ]:
age_array[0:5]


array([90, 82, 66, 54, 41])

In [ ]:
age_array[[0,2,4]]


array([90, 66, 41])

In [ ]:
# Boolean Indexing

condition = (age_array >= 25) & (age_array <= 35)

print("Boolean Condition:")
print(condition[:20])

print("\nAges between 25 and 35:")
print(age_array[condition][:20])


Boolean Condition:
[False False False False False  True False False False False False False
 False  True False False False False False  True]

Ages between 25 and 35:
[34 32 34 29 33 32 33 32 31 31 26 27 35 35 26 34 25 28 28 33]
